"""Render the ranked shortlist as an email-friendly HTML report."""
from __future__ import annotations

import html
from datetime import date
from pathlib import Path

from .models import ScoredJob

_ACCENT = "#2E4057"


def _badge_color(score: float) -> str:
    return "#2E7D32" if score >= 75 else "#F9A825" if score >= 60 else "#757575"


def _job_card(rank: int, scored: ScoredJob) -> str:
    j = scored.job
    color = _badge_color(scored.score)
    reasons = "".join(f"<li>{html.escape(r)}</li>" for r in scored.reasons)
    skills = ", ".join(html.escape(s) for s in scored.matched_skills[:8]) or "—"
    apply = (f'<a href="{html.escape(j.url)}" style="color:{_ACCENT};">Open posting →</a>'
             if j.url else "")
    b = scored.breakdown.as_dict()
    bars = " · ".join(f"{k.replace('_',' ')}: {v:.0f}" for k, v in b.items())
    llm = ' <span style="font-size:11px;color:#888;">(AI-scored)</span>' if scored.llm_used else ""

    return f"""
    <tr><td style="padding:14px 0;border-bottom:1px solid #eee;">
      <table width="100%"><tr>
        <td style="vertical-align:top;">
          <span style="font-size:18px;font-weight:700;color:{_ACCENT};">{rank}. {html.escape(j.title)}</span>{llm}<br>
          <span style="color:#444;">{html.escape(j.company)} · {html.escape(j.location or 'N/A')} · {html.escape(j.seniority)}</span>
        </td>
        <td style="text-align:right;vertical-align:top;white-space:nowrap;">
          <span style="background:{color};color:#fff;padding:4px 10px;border-radius:12px;font-weight:700;">
            {scored.score:.0f}/100</span>
        </td>
      </tr></table>
      <div style="margin:8px 0;color:#333;"><b>Matched skills:</b> {skills}</div>
      <ul style="margin:6px 0 6px 18px;color:#333;">{reasons}</ul>
      <div style="font-size:12px;color:#999;">{bars}</div>
      <div style="margin-top:4px;">{apply}</div>
    </td></tr>"""


def build_html(scored: list[ScoredJob], meta: dict) -> str:
    cards = "".join(_job_card(i, s) for i, s in enumerate(scored, 1))
    subtitle = (f"{meta.get('n_fetched', 0)} fetched → {meta.get('n_after_filter', 0)} after "
                f"filtering → top {len(scored)} shown")
    ai = "AI + heuristic" if meta.get("llm_used") else "heuristic"
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"></head>
    <body style="margin:0;background:#f4f5f7;">
    <table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px;">
      <table width="640" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:10px;
             font-family:Arial,Helvetica,sans-serif;">
        <tr><td style="background:{_ACCENT};color:#fff;padding:20px 24px;border-radius:10px 10px 0 0;">
          <div style="font-size:22px;font-weight:800;">🎯 Your Daily Job Matches</div>
          <div style="opacity:.85;font-size:13px;margin-top:4px;">{date.today().isoformat()} · {subtitle} · scored by {ai}</div>
        </td></tr>
        <tr><td style="padding:8px 24px 24px;"><table width="100%">{cards}</table></td></tr>
        <tr><td style="padding:16px 24px;color:#999;font-size:11px;border-top:1px solid #eee;">
          Generated by jobscreener. Scores are a fit estimate, not a guarantee — always read the full posting.
        </td></tr>
      </table>
    </td></tr></table></body></html>"""


def write_report(html_str: str, path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html_str, encoding="utf-8")
    return path
